# Alpine Linux with OpenJDK JRE
FROM openjdk:8-jre-alpine
# copy WAR into image
COPY /redeempromo-transaction-getpromobycode-1.2.0-SNAPSHOT.jar /redeempromo-transaction-getpromobycode.jar
# run application with this command line[
CMD ["java", "-jar", "/redeempromo-transaction-getpromobycode.jar"]
RUN apk add --no-cache tzdata
ENV TZ=Asia/Jakarta
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone
