apiVersion: v1
kind: Service
metadata:
  name: redeempromo-transaction-getpromobycode-v0102
spec:
  ports:
    - port: 80
      targetPort: 50012
      protocol: TCP
      name: http
  selector:
    app: redeempromo-transaction-getpromobycode-v0102
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redeempromo-transaction-getpromobycode-v0102
spec:
  selector:
    matchLabels:
      app: redeempromo-transaction-getpromobycode-v0102
  replicas: 1
  template:
    metadata:
      labels:
        app: redeempromo-transaction-getpromobycode-v0102
    spec:
      containers:
      - name: redeempromo-transaction-getpromobycode-v0102
        image: asia.gcr.io/amala-stg/getpromobycode-stg:v1.2
        imagePullPolicy: Always
        envFrom:
        - configMapRef:
            name: spring-active-profiles
        volumeMounts:
          - name: tz-jakarta
            mountPath: /etc/localtime
      volumes:
        - name: tz-jakarta
          hostPath:
            path: /usr/share/zoneinfo/Asia/Jakarta
            type: File
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: redeempromo-transaction-getpromobycode-v0102
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
spec:
  rules:
    - http:
        paths:
          - path: /amala/redeempromo/transaction/v1.2/getpromobycode
            backend:
              serviceName: redeempromo-transaction-getpromobycode-v0102
              servicePort: 80